### PR TITLE
Bdd files

### PR DESCRIPTION
**Pull request by tobyjaguar**
added the following files:
* environment.py
* shopcarts.feature
* shopcarts_steps.py
* web_steps.py

BDD was not run, files were just initially copied.

If behave is supposed to run, reject the PR

### CODE REVIEW

**Review by wjin17 — CHANGES_REQUESTED** [review]
You need to make the following changes to the vagrant file

1. version of Linux from bento to focal64
2. install linux chromium while setting up python libraries

```sh
######################################################################
# Setup a Python 3 development environment
######################################################################
config.vm.provision "shell", inline: <<-SHELL
apt-get update
apt-get install -y git tree wget vim jq python3-dev python3-pip python3-venv python3-selenium
apt-get -y autoremove

# Install Chromium Driver 
apt-get install -y chromium-chromedriver # <-- this line
```

**Comment by tobyjaguar** [comment]
thanks for this! 

complete.

**Comment by tobyjaguar** [comment]
I think we need to also add `python3-selenium` to the vagrant file as well

**Comment by wjin17** [comment]
lsat thing, 

```ssh
apt-get install -y git tree wget vim jq python3-dev python3-pip python3-venv python3-selenium # <-- add linux python3-selenium
```

that should be it!

**Comment by tobyjaguar** [comment]
This seems to cover it:
https://github.com/SU21-DevOps-Shopcart/shopcarts/blob/cd8f85ec2aabbd57c3d7365aac7aa8bd4d79c7cf/requirements.txt#L46

behave runs successful

**Review by wjin17 — APPROVED** [review]
looks good

**Comment by MiaozhiYu** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/631e9585-a2f8-4d46-ad54-13c6db4df5be?env_id=ibm:yp:us-south "nyu-shopcart-service-sum21-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/f78d95f4-669c-4021-869f-fda9437993d2 "nyu-shopcart-service-sum21") deployed [shopcarts](https://github.com/SU21-DevOps-Shopcart/shopcarts/releases/tag/deploy-ibm-yp-us-south-ls5501-nyu.edu-dev-20210723-162939 "deploy-ibm-yp-us-south-ls5501-nyu.edu-dev-20210723-162939") to [dev](https://console.bluemix.net/apps/b8917f81-f0f6-46b7-b965-eb161a5fa30f?env_id=ibm:yp:us-south "ibm:yp:us-south:ls5501@nyu.edu:dev"), including commit 2d44655e490565b03264dcaf49a4528a3d7560a7

**Comment by MiaozhiYu** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/631e9585-a2f8-4d46-ad54-13c6db4df5be?env_id=ibm:yp:us-south "nyu-shopcart-service-sum21-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/f78d95f4-669c-4021-869f-fda9437993d2 "nyu-shopcart-service-sum21") deployed [shopcarts](https://github.com/SU21-DevOps-Shopcart/shopcarts/releases/tag/deploy-ibm-yp-us-south-ls5501-nyu.edu-prod-20210725-211303 "deploy-ibm-yp-us-south-ls5501-nyu.edu-prod-20210725-211303") to [prod](https://console.bluemix.net/apps/0f1e4f28-e52d-45b9-bcf8-207de91d3a2d?env_id=ibm:yp:us-south "ibm:yp:us-south:ls5501@nyu.edu:prod"), including commit 2d44655e490565b03264dcaf49a4528a3d7560a7

**Comment by MiaozhiYu** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/631e9585-a2f8-4d46-ad54-13c6db4df5be?env_id=ibm:yp:us-south "nyu-shopcart-service-sum21-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/f78d95f4-669c-4021-869f-fda9437993d2 "nyu-shopcart-service-sum21") deployed [shopcarts](https://github.com/SU21-DevOps-Shopcart/shopcarts/releases/tag/deploy-ibm-yp-us-south-ls5501-nyu.edu-dev-20210803-211617 "deploy-ibm-yp-us-south-ls5501-nyu.edu-dev-20210803-211617") to [dev](https://console.bluemix.net/apps/b8917f81-f0f6-46b7-b965-eb161a5fa30f?env_id=ibm:yp:us-south "ibm:yp:us-south:ls5501@nyu.edu:dev"), including commit 2d44655e490565b03264dcaf49a4528a3d7560a7

**Comment by MiaozhiYu** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/631e9585-a2f8-4d46-ad54-13c6db4df5be?env_id=ibm:yp:us-south "nyu-shopcart-service-sum21-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/f78d95f4-669c-4021-869f-fda9437993d2 "nyu-shopcart-service-sum21") deployed [shopcarts](https://github.com/SU21-DevOps-Shopcart/shopcarts/releases/tag/deploy-ibm-yp-us-south-ls5501-nyu.edu-prod-20210803-212502 "deploy-ibm-yp-us-south-ls5501-nyu.edu-prod-20210803-212502") to [prod](https://console.bluemix.net/apps/0f1e4f28-e52d-45b9-bcf8-207de91d3a2d?env_id=ibm:yp:us-south "ibm:yp:us-south:ls5501@nyu.edu:prod"), including commit 2d44655e490565b03264dcaf49a4528a3d7560a7

**Comment by MiaozhiYu** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/631e9585-a2f8-4d46-ad54-13c6db4df5be?env_id=ibm:yp:us-south "nyu-shopcart-service-sum21-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/f78d95f4-669c-4021-869f-fda9437993d2 "nyu-shopcart-service-sum21") deployed [shopcarts](https://github.com/SU21-DevOps-Shopcart/shopcarts/releases/tag/deploy-ibm-yp-us-south-ls5501-nyu.edu-dev-20210805-034532 "deploy-ibm-yp-us-south-ls5501-nyu.edu-dev-20210805-034532") to [dev](https://console.bluemix.net/apps/b8917f81-f0f6-46b7-b965-eb161a5fa30f?env_id=ibm:yp:us-south "ibm:yp:us-south:ls5501@nyu.edu:dev"), including commit 2d44655e490565b03264dcaf49a4528a3d7560a7

**Pull request merged**
